---
- name: basename newest_package_file
  ansible.builtin.set_fact:
    newest_package_name: "{{ hostvars['localhost']['newest_package_path'] | basename }}"
  run_once: True

- name: push package to pxe
  ansible.builtin.copy:
    src: "{{ hostvars['localhost']['newest_package_path'] }}"
    dest: "{{ pxe_CD_package_path }}/{{ newest_package_name }}"
    force: yes
  ignore_errors: yes
  ignore_unreachable: yes
