- hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: choose_project
    - role: find_newest_package
      tags: [always]

- hosts: backup_server
  any_errors_fatal: true
  gather_facts: False
  roles:
    - role: choose_project
    - role: backup_package
      tags: [always]